# Generated by Django 4.1.5 on 2023-01-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='user delete', on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x7fd66e0e5960>'), to='bboard.user', verbose_name='Автор'),
        ),
    ]
