# Generated by Django 4.1.6 on 2023-02-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GamesDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDev', models.CharField(db_index=True, max_length=50, verbose_name='Разработчик')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
                'ordering': ['nameDev'],
            },
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Игра')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('upd_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('slug', models.SlugField()),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('game_image', models.ImageField(upload_to=None, verbose_name='Логотип игры')),
                ('is_active_game', models.BooleanField(verbose_name='Доступность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HW23.categories', verbose_name='Категория')),
                ('gameDev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HW23.gamesdev', verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['name'],
            },
        ),
    ]
