# Generated by Django 4.1.6 on 2023-02-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_image',
            field=models.ImageField(upload_to='HW23/images', verbose_name='Логотип игры'),
        ),
    ]
