# Generated by Django 4.1.6 on 2023-02-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0002_alter_games_game_image'),
    ]

    operations = [
    ]
