# Generated by Django 4.1.6 on 2023-02-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0003_auto_20230206_2109'),
    ]

    operations = [
    ]
