# Generated by Django 4.1.6 on 2023-02-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0006_status_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='game_amount',
            field=models.IntegerField(default=0, verbose_name='Игр в категории'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_image',
            field=models.ImageField(upload_to='images', verbose_name='Логотип игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='HW23.status', verbose_name='Статус'),
        ),
    ]
