# Generated by Django 4.1.6 on 2023-02-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0008_alter_games_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
