# Generated by Django 4.1.6 on 2023-02-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0009_alter_games_slug'),
    ]

    operations = [
        migrations.RenameField('Games', 'is_active_game', 'is_active'
        ),
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активация'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Адрес'),
        ),
        
    ]
