# Generated by Django 4.1.6 on 2023-02-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0011_games_is_active_game_alter_games_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='is_active_game',
        ),
    ]
