# Generated by Django 4.1.6 on 2023-02-27 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0013_games_index_name_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить на экран?')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('upd_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HW23.games', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-create_date'],
            },
        ),
    ]
