# Generated by Django 4.1.6 on 2023-02-28 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0014_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='rating_avg',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг'),
        ),
    ]
