# Generated by Django 4.1.6 on 2023-02-28 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0016_alter_comments_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='rating_avg',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг'),
        ),
    ]
