# Generated by Django 4.1.6 on 2023-02-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW23', '0017_alter_games_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='guest',
            field=models.BooleanField(default=False, verbose_name='Автор гость?'),
        ),
    ]
