# Generated by Django 4.1.5 on 2023-01-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('test', models.FloatField(null=True)),
                ('test2', models.FloatField(blank=True)),
                ('publisher', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
