# Generated by Django 4.1.5 on 2023-01-23 23:52

from django.db import migrations, models
import django.db.models.deletion
import func.validate


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, validators=[func.validate.Validator.validate_login], verbose_name='Ник')),
                ('firstname', models.CharField(max_length=150, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=150, validators=[func.validate.Validator.validate_email], verbose_name='E-mail')),
                ('password', models.CharField(max_length=150, validators=[func.validate.Validator.validate_password], verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['login'],
            },
        ),
        migrations.AlterModelOptions(
            name='bd',
            options={'ordering': ['-publisher'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RemoveField(
            model_name='bd',
            name='test',
        ),
        migrations.RemoveField(
            model_name='bd',
            name='test2',
        ),
        migrations.AlterField(
            model_name='bd',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='publisher',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Статья')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(default='user delete', on_delete=django.db.models.deletion.SET_DEFAULT, to='bboard.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-published'],
            },
        ),
    ]
